{ config, pkgs, lib, ... }:

let
  cfg = config.custom.nvidia;
in {
  options.custom.nvidia = {
    enable = lib.mkEnableOption "NVIDIA proprietary driver + CUDA stack";

    prime = {
      offload = lib.mkEnableOption "PRIME render offload (dGPU on demand)" // { default = true; };
      sync = lib.mkEnableOption "PRIME sync mode (dGPU always on, drives external outputs)";

      nvidiaBusId = lib.mkOption {
        type = lib.types.str;
        description = "PCI bus ID of the NVIDIA dGPU (e.g. PCI:100:0:0).";
      };

      otherBusId = lib.mkOption {
        type = lib.types.str;
        description = "PCI bus ID of the iGPU driving the display (e.g. PCI:101:0:0).";
      };

      otherBusIsAmd = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Whether the non-NVIDIA GPU is AMD (sets amdgpuBusId vs intelBusId).";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    # Mesa + Vulkan loaders, 32-bit shims for Steam/wine if ever needed.
    hardware.graphics = {
      enable = true;
      enable32Bit = true;
    };

    # Tells X/Wayland to load nvidia.
    services.xserver.videoDrivers = [ "nvidia" ];

    hardware.nvidia = {
      # Blackwell (RTX 50-series) needs a recent driver. `production` on
      # nixos-unstable is 570+ which supports GB20x.
      package = config.boot.kernelPackages.nvidiaPackages.production;

      # Open kernel module is required for Turing+ on modern drivers and
      # is the only supported path for Blackwell.
      open = true;

      modesetting.enable = true;

      powerManagement.enable = true;
      # Fine-grained suspend only makes sense with offload; sync keeps dGPU always on.
      powerManagement.finegrained = cfg.prime.offload;

      nvidiaSettings = true;

      prime = lib.mkIf (cfg.prime.offload || cfg.prime.sync) (
        { nvidiaBusId = cfg.prime.nvidiaBusId; }
        // (if cfg.prime.otherBusIsAmd
              then { amdgpuBusId = cfg.prime.otherBusId; }
              else { intelBusId  = cfg.prime.otherBusId; })
        // lib.optionalAttrs cfg.prime.offload {
          offload.enable = true;
          offload.enableOffloadCmd = true;
        }
        // lib.optionalAttrs cfg.prime.sync {
          sync.enable = true;
        }
      );
    };

    # The NVIDIA power-management systemd services — which run nvidia-sleep.sh to
    # save/restore dGPU VRAM around s2idle — are NOT generated by this nixpkgs
    # pin even though powerManagement.enable is set: the modprobe flag
    # (NVreg_PreserveVideoMemoryAllocations=1) gets applied but nothing is wired
    # into systemd-suspend.service. On this always-on PRIME-sync Blackwell dGPU
    # that missing save/restore step is what hard-resets the machine on wake from
    # sleep, so wire the hooks up explicitly. Remove this block if a future
    # driver/module bump starts providing them (a duplicate definition will
    # surface as an eval conflict).
    systemd.services =
      let
        sleepScript = "${config.hardware.nvidia.package}/bin/nvidia-sleep.sh";
        nvidiaService = state: {
          description = "NVIDIA system ${state} actions";
          path = [ pkgs.kbd ];
          serviceConfig = {
            Type = "oneshot";
            ExecStart = "${sleepScript} '${state}'";
          };
        };
      in lib.mkIf config.hardware.nvidia.powerManagement.enable {
        nvidia-suspend = nvidiaService "suspend" // {
          before = [ "systemd-suspend.service" ];
          requiredBy = [ "systemd-suspend.service" ];
        };
        nvidia-hibernate = nvidiaService "hibernate" // {
          before = [ "systemd-hibernate.service" ];
          requiredBy = [ "systemd-hibernate.service" ];
        };
        nvidia-resume = nvidiaService "resume" // {
          after = [ "systemd-suspend.service" "systemd-hibernate.service" ];
          requiredBy = [ "systemd-suspend.service" "systemd-hibernate.service" ];
        };
      };

    # CUDA build cache so we don't compile cuda-anything from source.
    nix.settings = {
      substituters = [ "https://cuda-maintainers.cachix.org" ];
      trusted-public-keys = [
        "cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E="
      ];
    };
  };
}
